language: java
deploy:
  provider: releases
  api_key:
    secure: R6ZSdzbH6R0RBkv2aMXsPhSBoCv4746TE7jJVaJiyXVDQSbdIW4j0NTG4+lOVpoG2nA93cG42cj63aS2OPTGjWlAjIuVPTGGnUdJz0b28xwHgHipEG6G7ikkP5GpGSoy++ZKJFSOpjpXWkSt4LyB1CVzjASsiE+B8pBpDz9n1jI=
  file: build/libs/database-conntest-plugin-1.0.0.jar
  on:
    repo: xebialabs-community/xld-database-conntest

